<main class="container p-4"> 
    <div class="flex flex-col">
        <section class="flex-grow">
            <p>contingut de la <b>TestUserView</b> ... /views/scripts/testUser/index.phtml file :)  </p>

            <!-- RENDERITZAT DE LA PAGINA  -->
            <?php 
                echo $this->showUser();
                // include "./app/controllers/UserController.php";
            ?>

        </section>
    </div>
</main>
